-- LaRae Dotson-- M04 Project-- April 12, 2024
CREATE TABLE CUSTOMERS13 (
    CUSTOMER_ID NUMBER(10) NOT NULL,
    LAST_NAME VARCHAR2(25) NOT NULL,
    FIRST_NAME VARCHAR2(25) NOT NULL,
    HOME_PHONE VARCHAR2(12) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(30) NOT NULL,
    STATE VARCHAR2(2) NOT NULL,
    EMAIL VARCHAR2(25),
    CELL_PHONE VARCHAR2(12),
    CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE MOVIES13 (
    TITLE_ID NUMBER(10) NOT NULL,
    TITLE VARCHAR2(60) NOT NULL,
    DESCRIPTION VARCHAR2(400),
    RATING VARCHAR2(4) NOT NULL,
    CATEGORY VARCHAR2(20) NOT NULL,
    RELEASE_DATE DATE,
    CONSTRAINT TITLE_ID_PK PRIMARY KEY (TITLE_ID)
);

CREATE TABLE MEDIA13 (
    MEDIA_ID NUMBER(10) NOT NULL,
    FORMAT VARCHAR2(3) NOT NULL,
    TITLE_ID NUMBER(10) NOT NULL,
    CONSTRAINT MEDIA_ID_PK PRIMARY KEY (MEDIA_ID),
    CONSTRAINT MEDIA_TITLEID_FK FOREIGN KEY (TITLE_ID) REFERENCES MOVIES(TITLE_ID)
);

CREATE TABLE RENTAL_HISTORY13 (
    MEDIA_ID NUMBER(10) NOT NULL,
    RENTAL_DATE DATE NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    RETURN_DATE DATE,
    CONSTRAINT RENTAL_HISTORY_PK PRIMARY KEY (MEDIA_ID, RENTAL_DATE),
    CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT MEDIA_ID_FK FOREIGN KEY (MEDIA_ID) REFERENCES MEDIA(MEDIA_ID)
);

CREATE TABLE ACTORS13 (
    ACTOR_ID NUMBER(10) NOT NULL,
    STAGE_NAME VARCHAR2(40),
    FIRST_NAME VARCHAR2(25) NOT NULL,
    LAST_NAME VARCHAR2(25) NOT NULL,
    BIRTH_DATE DATE,
    CONSTRAINT ACTOR_ID_PK PRIMARY KEY (ACTOR_ID)
);

CREATE TABLE STAR_BILLINGS13 (
    ACTOR_ID NUMBER(10) NOT NULL,
    TITLE_ID NUMBER(10) NOT NULL,
    COMMENTS VARCHAR2(40),
    CONSTRAINT STAR_BILLINGS_PK PRIMARY KEY (ACTOR_ID, TITLE_ID),
    CONSTRAINT ACTOR_ID_FK FOREIGN KEY (ACTOR_ID) REFERENCES ACTORS(ACTOR_ID),
    CONSTRAINT TITLE_ID_FK FOREIGN KEY (TITLE_ID) REFERENCES MOVIES(TITLE_ID)
);



ALTER TABLE CUSTOMERS ADD CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE MOVIES ADD CONSTRAINT TITLE_ID_PK PRIMARY KEY (TITLE_ID);
ALTER TABLE MEDIA ADD CONSTRAINT MEDIA_ID_PK PRIMARY KEY (MEDIA_ID);
ALTER TABLE RENTAL_HISTORY ADD CONSTRAINT RENTAL_HISTORY_PK PRIMARY KEY (MEDIA_ID, RENTAL_DATE);
ALTER TABLE ACTORS ADD CONSTRAINT ACTOR_ID_PK PRIMARY KEY (ACTOR_ID);
ALTER TABLE STAR_BILLINGS ADD CONSTRAINT STAR_BILLINGS_PK PRIMARY KEY (ACTOR_ID, TITLE_ID);


ALTER TABLE MEDIA ADD CONSTRAINT MEDIA_TITLEID_FK FOREIGN KEY (TITLE_ID) REFERENCES MOVIES(TITLE_ID);
ALTER TABLE RENTAL_HISTORY ADD CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID);
ALTER TABLE RENTAL_HISTORY ADD CONSTRAINT MEDIA_ID_FK FOREIGN KEY (MEDIA_ID) REFERENCES MEDIA(MEDIA_ID);
ALTER TABLE STAR_BILLINGS ADD CONSTRAINT ACTOR_ID_FK FOREIGN KEY (ACTOR_ID) REFERENCES ACTORS(ACTOR_ID);
ALTER TABLE STAR_BILLINGS ADD CONSTRAINT TITLE_ID_FK FOREIGN KEY (TITLE_ID) REFERENCES MOVIES(TITLE_ID);

ALTER TABLE MOVIES ADD CONSTRAINT CHK_MOVIE_RATING CHECK (RATING IN ('G', 'PG', 'PG13', 'R'));
ALTER TABLE MOVIES ADD CONSTRAINT CHK_MOVIE_CATEGORY CHECK (CATEGORY IN ('DRAMA', 'COMEDY', 'ACTION', 'CHILD', 'SCIFI', 'DOCUMENTARY'));

SELECT constraint_name, constraint_type, table_name
FROM user_constraints
WHERE table_name IN ('CUSTOMERS13', 'MOVIES13', 'MEDIA13', 'RENTAL_HISTORY13', 'ACTORS13', 'STAR_BILLINGS13');


INSERT INTO CUSTOMERS13 (CUSTOMER_ID, LAST_NAME, FIRST_NAME, HOME_PHONE, ADDRESS, CITY, STATE, EMAIL, CELL_PHONE)
VALUES (101, 'Palombo', 'Lisa', '716-270-2669', '123 Main St', 'Buffalo', 'NY', 'palombo@ecc.edu', '716-555-1212');
(102, 'Smith', 'John', '555-123-4567', '456 Oak St', 'New York', 'NY', 'john@example.com', '555-987-6543'),
(103, 'Johnson', 'Emily', '555-234-5678', '789 Elm St', 'Los Angeles', 'CA', 'emily@example.com', '555-876-5432'),
(104, 'Williams', 'Michael', '555-345-6789', '123 Maple St', 'Chicago', 'IL', 'michael@example.com', '555-765-4321'),
(105, 'Jones', 'Jessica', '555-456-7890', '567 Pine St', 'Houston', 'TX', 'jessica@example.com', '555-654-3210'),
(106, 'Brown', 'Daniel', '555-567-8901', '901 Cedar St', 'Philadelphia', 'PA', 'daniel@example.com', '555-543-2109'),
(107, 'Miller', 'Sarah', '555-678-9012', '234 Birch St', 'Phoenix', 'AZ', 'sarah@example.com', '555-432-1098');

INSERT INTO MOVIES13 (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES

(1, 'Remember the Titans', 'The true story of a newly appointed African-American coach and his high school team on their first season as a racially integrated unit.', 'PG', 'DRAMA', TO_DATE('2000-09-29', 'YYYY-MM-DD'));
(2, 'The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'R', 'DRAMA', TO_DATE('1994-09-23', 'YYYY-MM-DD')),
(3, 'Inception', 'A thief who enters the dreams of others to steal their secrets from their subconscious.', 'PG13', 'ACTION', TO_DATE('2010-07-16', 'YYYY-MM-DD')),
(4, 'Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.', 'PG13', 'DRAMA', TO_DATE('1994-07-06', 'YYYY-MM-DD')),
(5, 'The Dark Knight', 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham, the Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'PG13', 'ACTION', TO_DATE('2008-07-18', 'YYYY-MM-DD')),
(6, 'The Matrix', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 'R', 'ACTION', TO_DATE('1999-03-31', 'YYYY-MM-DD'));


INSERT INTO MEDIA13 (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (92, 'DVD', 1);

INSERT INTO MEDIA13 (MEDIA_ID, FORMAT, TITLE_ID)
VALUES (93, 'VHS', 1);


INSERT INTO RENTAL_HISTORY13 (MEDIA_ID, RENTAL_DATE, CUSTOMER_ID, RETURN_DATE)
VALUES 
(92, TO_DATE('2010-09-19', 'YYYY-MM-DD'), 101, TO_DATE('2010-09-20', 'YYYY-MM-DD'));
(93, TO_DATE('2011-09-19', 'YYYY-MM-DD'), 102, TO_DATE('2011-09-20', 'YYYY-MM-DD'));
(92, TO_DATE('2012-09-19', 'YYYY-MM-DD'), 103, TO_DATE('2012-09-20', 'YYYY-MM-DD'));


INSERT INTO ACTORS13 (ACTOR_ID, STAGE_NAME, FIRST_NAME, LAST_NAME, BIRTH_DATE)
VALUES 
(1001, 'Brad Pitt', 'William', 'Pitt', TO_DATE('1963-12-18', 'YYYY-MM-DD'));
(1002, 'Angelina Jolie', 'Angelina', 'Jolie', TO_DATE('1975-06-04', 'YYYY-MM-DD')),
(1003, 'Leonardo DiCaprio', 'Leonardo', 'DiCaprio', TO_DATE('1974-11-11', 'YYYY-MM-DD'));



INSERT INTO STAR_BILLINGS13 (ACTOR_ID, TITLE_ID, COMMENTS)
VALUES (1001, 2, 'Romantic Lead');
(1002, 1, 'Lead Actress');
(1003, 3, 'Lead Actor');




/* CREATE TABLE STAR_BILLINGS (
    ACTOR_ID NUMBER(10) NOT NULL,
    TITLE_ID NUMBER(10) NOT NULL,
    COMMENTS VARCHAR2(40),
    CONSTRAINT STAR_BILLINGS_PK PRIMARY KEY (ACTOR_ID, TITLE_ID),
    CONSTRAINT ACTOR_ID_FK FOREIGN KEY (ACTOR_ID) REFERENCES ACTORS(ACTOR_ID),
    CONSTRAINT TITLE_ID_FK FOREIGN KEY (TITLE_ID) REFERENCES MOVIES(TITLE_ID)
);


